#define REG_INSTAN_VOLTR 0xE000 // VOLTAGE PHASE A
#define REG_INSTAN_VOLTS 0xE001 // VOLTAGE PHASE B
#define REG_INSTAN_VOLTT 0xE002 // VOLTAGE PHASE C
#define REG_INSTAN_CURRR 0xE010 // CURRENT PHASE A
#define REG_INSTAN_CURRS 0xE011 // CURRENT PHASE B
#define REG_INSTAN_CURRT 0xE012 // CURRENT PHASE C
#define REG_INSTAN_WATTR 0xE030 // WATT PHASE A
#define REG_INSTAN_WATTS 0xE031 // WATT PHASE B
#define REG_INSTAN_WATTT 0xE032 // WATT PHASE C
#define REG_INSTAN_PFACT 0xE026 // POWER FACTOR
#define REG_INSTAN_FREQU 0xE060 // FREQUENCY

#define REG_ENERGY_KVARH 0x1E20  // TOU ENERGY KVARH
#define REG_ENERGY_KWHLBP 0x1E01 // TOU ENERGY
#define REG_ENERGY_KWHBP 0x1E02
#define REG_ENERGY_KWHTOT 0x1E00
