#define TYPE_MK10E // TYPE METER EDMI MK10E
// #define TYPE_MK6N                // TYPE METER EDMI MK6N
#define RX_TIMEOUT 500  // MAX TIMEOUT IN RX
#define CHAR_RX_ACK 3   // MAX ACK MESSAGE FROM METER WITHOUT BODY
#define CHAR_RX_DATA 50 // MAX RX DATA
#define CHAR_SERIALNUM 10
#define CHAR_DATA_FLOAT 4          // MAX 32bit FLOAT
const int INTERCHAR_TIMEOUT = 100; // MAX TIMEOUT EVERY CHAR
